postgres:
    sudo docker run --name postgres12 -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgress -d postgres


createdb:
    sudo docker exec -it postgres12 createdb --username=postgres go_bank

dropdb:
    sudo docker exec -it postgres12 dropdb go_bank

.PHONY: postgres createdb dropdb